#!/bin/bash

set -o nounset -o errexit -o pipefail

# `-noout` to avoid outputting EC parameters.
# `-genkey` and `-out` to write P-256 private key.
openssl ecparam -name P-256 -noout -genkey -out private_key.pem

# Read private key, write public key.
openssl pkey -in private_key.pem -pubout -out public_key.pem

cat *.pem
