#!/bin/bash

set -o nounset -o errexit -o pipefail

# Replace with the ID of your authorized_keys Google Doc.
GOOGLE_DOC_ID=4oVJ6K5g2LOhqlgrblto5WYTasVebsPJGbsHSmVXNyQe

curl --silent --fail "https://docs.google.com/document/export?id=${GOOGLE_DOC_ID}&format=txt"
